baseURL = "https://www.prosearium.net"
languageCode = "en-us"
title = "Prosearium.net"
theme = "kross"
summaryLength = "10"

# Plugins
[params.plugins]

  # CSS Plugins
  [[params.plugins.css]]
  URL = "plugins/bootstrap/bootstrap.min.css"
  [[params.plugins.css]]
  URL = "plugins/slick/slick.css"
  [[params.plugins.css]]
  URL = "plugins/themify-icons/themify-icons.css"

  # JS Plugins
  [[params.plugins.js]]
  URL = "plugins/jQuery/jquery.min.js"
  [[params.plugins.js]]
  URL = "plugins/bootstrap/bootstrap.min.js"
  [[params.plugins.js]]
  URL = "plugins/slick/slick.min.js"
  [[params.plugins.js]]
  URL = "plugins/shuffle/shuffle.min.js"


# navigation
[menu]

  [[menu.main]]
  name = "About"
  URL = "about"
  weight = 2

  [[menu.main]]
  name = "Blog"
  URL = "blog"
  weight = 3

  [[menu.main]]
  name = "Games"
  URL = "games"
  weight = 4

  [[menu.main]]
  name = "Contact"
  URL = "contact"
  weight = 5


[params]
logo = "images/logo.png"
home = "Home"
# Meta data
description = "An initiative to get 1000 African women of all backgrounds to create and upload their own games."
author = "Sithe Ncube"
# Google Analitycs
googleAnalitycsID = "UA-153215157-1"

  # Preloader
  [params.preloader]
  enable = true

  [params.contact]
  enable = true
  formAction = "https://formspree.io/mdokaroq" #contact form works with formspree.io

  [params.footer]
  email = "hello@prosearium.net"
  phone = ""
  address = "Wakanda"
